name: 🐛 Bug Report
description: Something isn't working
title: "[Bug]: "
labels: ["🐛 Type: Bug"]
assignees:
  - malezjaa
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: "Is there an existing issue for this?"
      description: "Please search [here](../issues?q=is%3Aissue) to see if an issue already exists for the bug you encountered"
      options:
        - label: "I have searched the existing issues"
          required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Describe the issue here.
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Expected behavior"
      description: "A clear and concise description of what you expected to happened (or code)"

  - type: textarea
    attributes:
      label: "Steps to reproduce"
      description: |
        What steps can we follow to reproduce the issue?

  - type: dropdown
    id: operating-systems
    attributes:
      label: What type of Operating System are you seeing the problem on?
      multiple: true
      options:
        - Linux
        - Windows
        - Mac
        - Other
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Code to produce this issue.
      description: Please copy and paste any relevant code to re-produce this issue.
